services:

  odoo:
    image: odoo:18
    container_name: odoo
    restart: unless-stopped 
    depends_on:
      - db
    ports:
      - "8201:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=${ODOO_HOST}
      - USER=${ODOO_USER}
      - PASSWORD=${ODOO_PASSWORD}
    networks:
      - general-net
    command: odoo -d ${ODOO_USER} --db_user=${ODOO_USER} --db_password=${ODOO_PASSWORD} -i base      

  db:
    image: postgres:16.0
    container_name: db
    restart: unless-stopped       
    environment:
      - POSTGRES_DB=${ODOO_USER}
      - POSTGRES_PASSWORD=${ODOO_PASSWORD}
      - POSTGRES_USER=${ODOO_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - general-net

volumes:
  odoo-data:
  db-data:    

networks:
  general-net:
    external: true  # Usa la red ya creada
